### ISSUE TITLE
Creating waveform error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [quemoni/subtitleedit#140]
```
What steps will reproduce the problem?
1.New project
2.Open a video file
3.Click to add waveform and create wave graph

What is the expected output? What do you see instead?
The wave graph should show up after a short while, instead i get a pop-up the 
moment I click to add waveform

What version of the product are you using? On what operating system?
The problem occurs with both 3.2.8 and 3.3.4 version
Windows 7 

Please provide any additional information below.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.SEHException: External component has thrown an 
exception.
   at Microsoft.Win32.NativeMethods.ShellExecuteEx(ShellExecuteInfo info)
   at System.Diagnostics.ShellExecuteHelper.ShellExecuteFunction()
   at System.Diagnostics.ShellExecuteHelper.ShellExecuteOnSTAThread()
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Nikse.SubtitleEdit.Forms.AddWareForm.buttonRipWave_Click(Object sender, EventArgs e)
   at Nikse.SubtitleEdit.Forms.AddWareForm.AddWareForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5466 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
SubtitleEdit
    Assembly Version: 3.3.4.1785
    Win32 Version: 3.3.4.1785
    CodeBase: file:///C:/Program%20Files/Subtitle%20Edit/SubtitleEdit.exe
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5468 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
mscorlib.resources
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5466 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Interop.QuartzTypeLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Subtitle%20Edit/Interop.QuartzTypeLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


The screenshot is attached, however I use this program in Korea so the popup in 
the screenshot is in Korean.


```

Original issue reported on code.google.com by `kay...@gmail.com` on 26 Apr 2013 at 1:25

Attachments:
- [screenshot.jpg](https://storage.googleapis.com/google-code-attachments/subtitleedit/issue-140/comment-0/screenshot.jpg)

**Comment by GoogleCodeExporter** [comment]
```
Try re-installing VLC 2.0.6 32-bit... any better?
```

Original comment by `nikse.dk@gmail.com` on 26 Apr 2013 at 5:54

**Comment by GoogleCodeExporter** [comment]
```
I tried it already and it still didn't work. is there any other way I could
get it fixed? I really need that program.
Thank you.
```

Original comment by `kay...@gmail.com` on 29 Apr 2013 at 1:25

**Comment by GoogleCodeExporter** [comment]
```
You can extract a 16-bit stereo wave file with either VLC interface, FFMPEG, or 
another program - and then drag'n'drop the generated wave file on the waveform 
in SE.

Also, it's best to have a few gigabytes free space on drive C: (or where you 
temp folder is located)
```

Original comment by `nikse.dk@gmail.com` on 29 Apr 2013 at 5:30

**Comment by GoogleCodeExporter** [comment]
```
Some improvements has been made in SE 3.3.11 regarding audio extraction - and 
in Options -> Settings -> Waveform/spectrogram, you can choose FFMPEG for 
extraction audio instead of VLC.

Also, SE will now display a red warning if disk space is low.
```

Original comment by `nikse.dk@gmail.com` on 6 Dec 2013 at 6:54
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I have problem with Creating waveform...until yesterday all was going go..but 
today I clik and I am waiting and wait ...but  waveform wasn;t there. I have 
once more time this problem and I was re-installing VLC 2.0.6 32-bit... and was 
ok...but now I dont know haw many time I have installing and re-instanlling VLC 
and the subtitle edit it still didn't work :( I love this programme and I need 
it..what can I do? Please...:(
```

Original comment by `loucin...@gmail.com` on 1 Apr 2014 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
Now I have 3.31.4 portable edition..until yestrday I was working with 
SE333..thks very much
```

Original comment by `loucin...@gmail.com` on 1 Apr 2014 at 6:30

**Comment by GoogleCodeExporter** [comment]
```
I have problem to create waveform, one day ok, the next day... totally wrong.
What about problems? 
I have yet reinstalled VLC, and also SE. Could be a hard disk space problem????
```

Original comment by `polgh...@gmail.com` on 5 Jun 2015 at 2:43
