### ISSUE TITLE
SUP export does NOT work.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [quemoni/subtitleedit#151]
```
What steps will reproduce the problem?
1. Select File > Import/OCR Bluray sup file. 
2. In import window right click on subtitle list and select Export > Bluray sup.
3. In next window click Export all lines.
4. Choose target file and click Save.


What is the expected output? What do you see instead?

Expected: Saved SUP file.
Resulted: Exception:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an 
object.
   at Nikse.SubtitleEdit.Forms.ExportPngXml.WriteParagraph(Int32 width, StringBuilder sb, Int32 border, Int32 height, Int32 imagesSavedCount, VobSubWriter vobSubWriter, FileStream binarySubtitleFile, MakeBitmapParameter param, Int32 i)
   at Nikse.SubtitleEdit.Forms.ExportPngXml.ButtonExportClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3643 (GDR.050727-3600)
    CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
SubtitleEdit
    Assembly Version: 3.3.5.1862
    Win32 Version: 3.3.5.1862
    CodeBase: file:///C:/SE/SubtitleEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3645 (GDR.050727-3600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3644 (GDR.050727-3600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3644 (GDR.050727-3600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
NHunspell
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/SE/NHunspell.DLL
---------------------------------------- 


What version of the product are you using? On what operating system?
Confirmed on 3.3.4 and 3.3.5 on Win XP and Win 7.
```

Original issue reported on code.google.com by `webmas...@cvut.cz` on 14 Jun 2013 at 2:10

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r1871.
```

Original comment by `nikse.dk@gmail.com` on 14 Jun 2013 at 3:02
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
You can test it via latest svn or here: http://www.nikse.dk/SubtitleEdit.zip
```

Original comment by `nikse.dk@gmail.com` on 14 Jun 2013 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
Works like a charm! Thank you and BIG thumbs up for lightning fast response!
```

Original comment by `webmas...@cvut.cz` on 17 Jun 2013 at 2:09
