### ISSUE TITLE
Unhandled exception after OCRing .sup subtitles

### ISSUE THREAD

**Issue by GoogleCodeExporter** [quemoni/subtitleedit#31]
```
What steps will reproduce the problem?
1. Import .sup file
2. Suffer through OCR process correcting as you go

What is the expected output? What do you see instead?
Instead of seeing the fruit of my OCR labor, all work is lost.

What version of the product are you using? On what operating system?
3.2, build 29279 on Win7 64bit.

Please provide any additional information below.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an 
object.
   at Nikse.SubtitleEdit.Logic.BluRaySup.BluRaySupPicture.get_ObjectIdImage()
   at Nikse.SubtitleEdit.Logic.BluRaySup.BluRaySupPicture.DecodeImage(BluRaySupPalette defaultPalette)
   at Nikse.SubtitleEdit.Forms.VobSubOcr.GetSubtitleBitmap(Int32 index)
   at Nikse.SubtitleEdit.Forms.VobSubOcr.ShowSubtitleImage(Int32 index)
   at Nikse.SubtitleEdit.Forms.VobSubOcr.ButtonStartOcrClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5446 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
SubtitleEdit
    Assembly Version: 3.2.0.29279
    Win32 Version: 3.2.0.29279
    CodeBase: file:///D:/_web_dl/SE32Beta1/SubtitleEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5446 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5442 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
NHunspell
    Assembly Version: 0.9.6.0
    Win32 Version: 0.9.6.0
    CodeBase: file:///D:/_web_dl/SE32Beta1/NHunspell.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

Original issue reported on code.google.com by `cnan...@gmail.com` on 28 Jun 2011 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
Could you supply the sup file?
```

Original comment by `nikse.dk@gmail.com` on 28 Jun 2011 at 4:22

**Comment by GoogleCodeExporter** [comment]
```
Here:
http://dl.dropbox.com/u/32571/GLADIATOR_EX%20-%20ID9%20-%20en-English.sup

Generated via latest version of Staxrip during Blu-ray import.
```

Original comment by `cnan...@gmail.com` on 28 Jun 2011 at 4:33

**Comment by GoogleCodeExporter** [comment]
```
Thx for the file :)

This bug should be fixed now (it does not crash any more, but shows an empty 
picture for last subtitle). You can get latest version from svn or here: 
http://www.nikse.dk/SubtitleEdit.zip (exe only - replace SubtitleEdit.exe in 
existing installation)
```

Original comment by `nikse.dk@gmail.com` on 28 Jun 2011 at 7:57
- Changed state: **Fixed**
