### ISSUE TITLE
System.ArgumentException: Stream is too small

### ISSUE THREAD

**Issue by GoogleCodeExporter** [quemoni/subtitleedit#32]
```
What steps will reproduce the problem?
1. New project
2. Open .mp4 Video
3. Click to add waveform and create the wav graph

What is the expected output? What do you see instead?
There should be a wave graph, after about 10 secs, I get a pop-up error, 
unhandled exception error.

What version of the product are you using? On what operating system?
Subtitle Edit 3.1, build 36527
Windows 7 Enterprise, 32 Bit

Please provide any additional information below.

See attachment also below is the content of the unhandled exception error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Stream is too small
   at Nikse.SubtitleEdit.Logic.WaveHeader..ctor(Stream stream)
   at Nikse.SubtitleEdit.Logic.WavePeakGenerator.Initialize(Stream stream)
   at Nikse.SubtitleEdit.Logic.WavePeakGenerator..ctor(String fileName)
   at Nikse.SubtitleEdit.Forms.AddWareForm.ReadWaveFile(String targetFile)
   at Nikse.SubtitleEdit.Forms.AddWareForm.buttonRipWave_Click(Object sender, EventArgs e)
   at Nikse.SubtitleEdit.Forms.AddWareForm.AddWareForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4961 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
SubtitleEdit
    Assembly Version: 3.1.0.36527
    Win32 Version: 3.1.0.36527
    CodeBase: file:///C:/Program%20Files/Subtitle%20Edit/SubtitleEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4961 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4957 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Interop.QuartzTypeLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Subtitle%20Edit/Interop.QuartzTypeLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

Original issue reported on code.google.com by `ozri...@gmail.com` on 9 Jul 2011 at 7:56

Attachments:
- [subtitle_edit_wav.jpg](https://storage.googleapis.com/google-code-attachments/subtitleedit/issue-32/comment-0/subtitle_edit_wav.jpg)

**Comment by GoogleCodeExporter** [comment]
```
Yes, this is a problem - seems to occur with smaller videos.
Latest beta has a better error message, but it still fails.

It's because VLC cannot extract the wave file! 
You can try via the command line: vlc.exe -I dummy -vvv --no-sout-video --sout 
#transcode{acodec=s16l}:std{mux=wav,access=file,dst="C:\Temp\out.wav"} 
"C:\Temp\input.mp4"

If anybody has any ideas let me know!
```

Original comment by `nikse.dk@gmail.com` on 9 Jul 2011 at 9:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `nikse.dk@gmail.com` on 5 Jan 2012 at 2:15
- Changed state: **Fixed**
