### ISSUE TITLE
Crash in Microsoft Translate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [quemoni/subtitleedit#50]
```
[spoiler]See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Web.Services.Protocols.SoapHeaderException: TranslateApiException: AppId 
is over the quota : ID=3641.V2_Soap.Translate.48BC9529
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at Nikse.SubtitleEdit.MicrosoftTranslationService.SoapService.Translate(String appId, String text, String from, String to, String contentType, String category)
   at Nikse.SubtitleEdit.Forms.GoogleTranslate.DoMicrosoftTranslate(String from, String to)
   at Nikse.SubtitleEdit.Forms.GoogleTranslate.buttonTranslate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4961 (win7RTMGDR.050727-4900)
    CodeBase: file:///G:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
SubtitleEdit
    Assembly Version: 3.2.2.25663
    Win32 Version: 3.2.2.25663
    CodeBase: file:///G:/Users/Gerry/Desktop/Software/subedit/SubtitleEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4961 (win7RTMGDR.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4962 (win7RTMGDR.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4955 (win7RTMGDR.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Web.Services
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_MSIL/System.Web.Services/2.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ujtdzexw
    Assembly Version: 3.2.2.25663
    Win32 Version: 2.0.50727.4962 (win7RTMGDR.050727-4900)
    CodeBase: file:///G:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


[spoiler/]
```

Original issue reported on code.google.com by `suryage...@gmail.com` on 31 Oct 2011 at 11:20

**Comment by GoogleCodeExporter** [comment]
```
im using win7
version 3.2.2
build 25663
```

Original comment by `suryage...@gmail.com` on 31 Oct 2011 at 11:21

**Comment by GoogleCodeExporter** [comment]
```
Sorry, but MS has closed their free translating service.
In next version MS translate will be gone...
```

Original comment by `nikse.dk@gmail.com` on 6 Nov 2011 at 11:11
- Changed state: **Fixed**
